name: Atualizar Playlist IPTV
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # ADICIONE ESTAS DUAS LINHAS ABAIXO:
    permissions:
      contents: write
      
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install requests

      - name: Executar Script
        run: python app.py
        env:
          XTREAM_HOST: ${{ secrets.XTREAM_HOST }}
          XTREAM_USER: ${{ secrets.XTREAM_USER }}
          XTREAM_PASS: ${{ secrets.XTREAM_PASS }}

      - name: Salvar alterações no GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u
          # O comando abaixo evita erro se não houver mudanças na lista
          git commit -m "Playlist atualizada automaticamente" || echo "Sem mudanças para salvar"
          git push
